spring.application.name=PS12345XTH.BinhTQ
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/fpoly_spring_core?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
# ---------------------------------------------------------
# ?Ã S?A: Thay ??i username và password thành user m?i t?o
spring.datasource.username=spring_user
spring.datasource.password=spring123
# ---------------------------------------------------------
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Kích ho?t tính n?ng Hibernate t? quét sinh b?ng ho?c c?p nh?t c?u trúc c?t t? ??ng t? mã Java
spring.jpa.hibernate.ddl-auto=update
# Gi? cho Spring Boot trì hoãn kh?i t?o d? li?u SQL cho ??n khi Hibernate ?ã t?o b?ng xong
spring.jpa.defer-datasource-initialization=true
# Ép bu?c in rõ câu l?nh SQL ch?y ng?m xu?ng màn hình ?? theo dõi debug
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true